FROM erlang:27.3.0.0

RUN apt-get update && apt-get -y install \
    emacs \
    bash-completion \
    git \
    inotify-tools \
    cmake \
    mosquitto

# promt> make c-tab-tab-ompile
RUN echo ". /etc/bash_completion" >> /root/.bashrc
